# Generated by Django 2.0 on 2019-06-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('data', models.DateTimeField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
    ]
