# Generated by Django 2.0 on 2019-06-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_uploadfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
